services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5204:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5204

  frontend:
    image: spa
    build:
      context: ./spa
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - webapi
