name: Docker Compose CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-run:
    runs-on: IVANZERG

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run services with Docker Compose
        run: docker-compose -f compose.yaml up --build -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start..."
          sleep 15 # adjust this as needed

      # Optional: curl to check services are up
      - name: Test backend
        run: curl --fail http://localhost:5204 || exit 1

      - name: Test frontend
        run: curl --fail http://localhost:5000 || exit 1

      - name: Shut down Docker Compose
        run: docker-compose -f compose.yaml down
